---
- name: Install K3s on master
  hosts: master
  become: yes
  tasks:
    - name: Install K3s server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
          --tls-san 10.0.10.11 \
          --disable traefik \
          --disable servicelb \
          --disable local-storage \
          --write-kubeconfig-mode 644" sh -s -
      args:
        creates: /usr/local/bin/k3s

    - name: Retrieve node token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      run_once: true

    - name: Save token for workers
      delegate_to: localhost
      ansible.builtin.copy:
        dest: ./k3s_token.txt
        content: "{{ k3s_token.stdout }}"

# ----------------------------------------------------------
# Workers
# ----------------------------------------------------------
- name: Install K3s on workers
  hosts: workers
  become: yes
  tasks:
    - name: Read master token
      ansible.builtin.slurp:
        src: ./k3s_token.txt
      register: token_file
      delegate_to: localhost

    - name: Install K3s agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://10.0.10.11:6443 \
        K3S_TOKEN={{ token_file['content'] | b64decode }} sh -
      args:
        creates: /usr/local/bin/k3s-agent

# ----------------------------------------------------------
# kubeconfig setup on Ansible controller
# ----------------------------------------------------------
- name: Retrieve kubeconfig from master
  hosts: master
  tasks:
    - name: Fetch kubeconfig
      become: yes
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/.kube/config"
        flat: yes

- name: Prepare kubeconfig and install kubectl
  hosts: localhost
  tasks:

    - name: Ensure ~/.kube directory exists
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/.kube"
        state: directory
        mode: '0700'

    - name: Replace localhost with master IP in kubeconfig
      ansible.builtin.replace:
        path: "{{ lookup('env','HOME') }}/.kube/config"
        regexp: '127\.0\.0\.1'
        replace: '10.0.10.11'

    # ------------------------------------------------------
    # kubectl installation (ARM64, non-sudo compatible)
    # ------------------------------------------------------
    - name: Download kubectl (binary)
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ lookup('pipe','curl -L -s https://dl.k8s.io/release/stable.txt') }}/bin/linux/arm64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'

    - name: Install kubectl to ~/.local/bin for non-root user
      ansible.builtin.shell: |
        mkdir -p ~/.local/bin
        mv /tmp/kubectl ~/.local/bin/kubectl
        chmod +x ~/.local/bin/kubectl
      args:
        executable: /bin/bash

    - name: Ensure ~/.local/bin is in PATH permanently
      ansible.builtin.lineinfile:
        path: "{{ lookup('env','HOME') }}/.bashrc"
        regexp: 'export PATH=.*\.local/bin'
        line: 'export PATH="$HOME/.local/bin:$PATH"'
        insertafter: EOF

    # ------------------------------------------------------
    # Run K3s bootstrap script as kagiso
    # ------------------------------------------------------

- name: Run K3s bootstrap script
  hosts: localhost
  tasks:

    - name: Ensure script is executable (needs root only if permissions are restricted)
      ansible.builtin.file:
        path: "{{ playbook_dir }}/bootstrap-k3s.sh"
        mode: '0755'
      become: yes

    - name: Run the K3s bootstrap script as kagiso
      ansible.builtin.shell: |
        export HOME="/home/kagiso"
        export KUBECONFIG="/home/kagiso/.kube/config"
        export PATH="$HOME/.local/bin:$PATH"
        bash "{{ playbook_dir }}/bootstrap-k3s.sh"
      args:
        executable: /bin/bash
      become: yes
      become_user: kagiso
