apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.kagiso.me:8200"
      path: "kv/data"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
