---
- name: Install K3s on master
  hosts: master
  become: yes
  tasks:
    - name: Install K3s server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
          --tls-san 10.0.10.11 \
          --disable traefik \
          --disable servicelb \
          --disable local-storage \
          --write-kubeconfig-mode 644" sh -s -
      args:
        creates: /usr/local/bin/k3s

    - name: Retrieve node token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      run_once: true

    - name: Save token for workers
      delegate_to: localhost
      ansible.builtin.copy:
        dest: ./k3s_token.txt
        content: "{{ k3s_token.stdout }}"

- name: Install K3s on workers
  hosts: workers
  become: yes
  tasks:
    - name: Read master token
      ansible.builtin.slurp:
        src: ./k3s_token.txt
      register: token_file
      delegate_to: localhost

    - name: Install K3s agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://10.0.10.11:6443 \
        K3S_TOKEN={{ token_file['content'] | b64decode }} sh -
      args:
        creates: /usr/local/bin/k3s-agent


####################################################################
# 1️⃣ - Configure Kubeconfig on Ansible control host (for Helm)
####################################################################
- name: Retrieve kubeconfig from master
  hosts: master
  tasks:
    - name: Fetch kubeconfig
      become: yes
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/kubeconfig"
        flat: yes

- name: Prepare kubeconfig for local Helm/Kubectl use
  hosts: localhost
  tasks:
    - name: Replace localhost with master IP
      ansible.builtin.replace:
        path: ./kubeconfig
        regexp: '127\.0\.0\.1'
        replace: '10.0.10.11'


####################################################################
# 2️⃣ - Install MetalLB
####################################################################
- name: Deploy MetalLB
  hosts: master
  become: false
  tasks:
    - name: Add MetalLB Helm repo
      ansible.builtin.shell: helm repo add metallb https://metallb.github.io/metallb && helm repo update

    - name: Install MetalLB via Helm
      ansible.builtin.shell: |
        helm upgrade --install metallb metallb/metallb \
          --namespace metallb-system --create-namespace
      environment:
        KUBECONFIG: ./kubeconfig

    - name: Configure MetalLB address pool
      ansible.builtin.copy:
        dest: ./metallb-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-address-pool
            namespace: metallb-system
          spec:
            addresses:
              - 10.0.10.110-10.0.10.129
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2adv
            namespace: metallb-system
      delegate_to: localhost

    - name: Apply MetalLB address pool config
      ansible.builtin.shell: kubectl apply -f ./metallb-config.yaml
      environment:
        KUBECONFIG: ./kubeconfig


####################################################################
# 3️⃣ - Install Cert-Manager
####################################################################
- name: Deploy Cert-Manager
  hosts: localhost
  become: false
  tasks:
    - name: Install Cert-Manager via kubectl
      ansible.builtin.shell: |
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.0/cert-manager.yaml


#  ####################################################################
#  # 4️⃣ - Install Longhorn (storage)
#  ####################################################################
#  - name: Deploy Longhorn
#    hosts: localhost
#    become: false
#    tasks:
#      - name: Install Longhorn via kubectl
#        ansible.builtin.shell: |
#          kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.9.3/deploy/longhorn.yaml


####################################################################
# 5️⃣ - Install Traefik (custom values)
####################################################################
- name: Deploy Traefik with custom values
  hosts: master
  become: false
  tasks:
    - name: Add Traefik Helm repo
      ansible.builtin.shell: helm repo add traefik https://traefik.github.io/charts && helm repo update

    - name: Copy Traefik values file
      ansible.builtin.copy:
        dest: ./traefik-values.yaml
        content: |
          globalArguments:
            - "--global.sendanonymoususage=false"
            - "--global.checknewversion=false"
          additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"
            - "--log.level=INFO"
          deployment:
            enabled: true
            replicas: 3
          ports:
            web:
              redirections:
                entrypoint:
                  to: websecure
                  priority: 10
            websecure:
              http3:
                enabled: true
              advertisedPort: 443
              tls:
                enabled: true
          ingressRoute:
            dashboard:
              enabled: false
          providers:
            kubernetesCRD:
              enabled: true
              ingressClass: traefik
              allowExternalNameServices: true
            kubernetesIngress:
              enabled: true
              allowExternalNameServices: true
              publishedService:
                enabled: false
          rbac:
            enabled: true
          service:
            enabled: true
            type: LoadBalancer
            spec:
              loadBalancerIP: 10.0.10.110
          loadBalancerSourceRanges: []
          externalIPs: []

    - name: Install Traefik via Helm
      ansible.builtin.shell: |
        helm upgrade --install traefik traefik/traefik \
          --namespace traefik \
          -f ./traefik-values.yaml
      environment:
        KUBECONFIG: ./kubeconfig
