---
- name: Install K3s on master
  hosts: master
  become: yes
  tasks:
    - name: Install K3s server
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server \
          --tls-san 10.0.10.11 \
          --disable traefik \
          --disable servicelb \
          --disable local-storage \
          --write-kubeconfig-mode 644" sh -s -
      args:
        creates: /usr/local/bin/k3s

    - name: Retrieve node token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false
      run_once: true

    - name: Save token for workers
      delegate_to: localhost
      ansible.builtin.copy:
        dest: ./k3s_token.txt
        content: "{{ k3s_token.stdout }}"


- name: Install K3s on workers
  hosts: workers
  become: yes
  tasks:
    - name: Read master token
      ansible.builtin.slurp:
        src: ./k3s_token.txt
      register: token_file
      delegate_to: localhost

    - name: Install K3s agent
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://10.0.10.11:6443 \
        K3S_TOKEN={{ token_file['content'] | b64decode }} sh -
      args:
        creates: /usr/local/bin/k3s-agent


####################################################################
# Retrieve kubeconfig from master onto Ansible host
####################################################################
- name: Retrieve kubeconfig from master
  hosts: master
  tasks:
    - name: Fetch kubeconfig
      become: yes
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env','HOME') }}/kubeconfig"
        flat: yes


####################################################################
# Fix kubeconfig + install kubectl on the controller (RPi)
####################################################################
- name: Prepare kubeconfig and install kubectl
  hosts: localhost
  tasks:
    - name: Replace localhost with master IP in kubeconfig
      ansible.builtin.replace:
        path: "{{ lookup('env','HOME') }}/kubeconfig"
        regexp: '127\.0\.0\.1'
        replace: '10.0.10.11'

    - name: Check if kubectl exists
      ansible.builtin.command: kubectl version --client --short
      register: kubectl_check
      ignore_errors: true

    - name: Install kubectl for kagiso user (no sudo)
      ansible.builtin.shell: |
        set -e
        ARCH=arm64
        VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)

        # Download kubectl binary + checksum
        curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/${ARCH}/kubectl"
        curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/${ARCH}/kubectl.sha256"

        # Verify checksum
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

        # Install locally without sudo
        chmod +x kubectl
        mkdir -p ~/.local/bin
        mv kubectl ~/.local/bin/kubectl
      args:
        executable: /bin/bash
      when: kubectl_check.rc != 0
